[package]
name = "waves-protobuf-schemas"
version = "1.2.7-SNAPSHOT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.2"
prost = "0.6"

[build-dependencies]
tonic-build = "0.2.0"
